import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

 const RootLayout =({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className='text-white text-xl bg-slate-500 h-16 flex items-center justify-center '>
        <a className='pr-5' href="/"> About</a>
        <a className='pr-5' href="/"> Contact</a>
        <a className='pr-5' href="/"> Home</a>
        <a className='pr-5' href="/"> Blog</a>
        <a className='pr-5' href="/"> Bla Bla</a>
      </nav>
        
        {children}
      <footer>Footer</footer>
        </body>
    </html>
  )
}
export default RootLayout;
